### ISSUE TITLE
Tips for getting started?!

### ISSUE THREAD

**Issue by VashonSoftware** [dnnconsulting/DnnC.MDesign#1]
On the readme.md (on the project's home page) a bug with the 8.0.0's portals/web.config file is mentioned. I've just applied this skin and am not sure if I need to add some background files or alter my web.config more than I have.

Does this bug apply to 8.0.2 too? That portals/web.config reads:

```
**<host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>**
<pages pageBaseType="DotNetNuke.Web.Mvc.Framework.DnnWebViewPage">
  <namespaces>
    <add namespace="System.Linq"/>
    <add namespace="System.Web.Mvc"/>
    <add namespace="System.Web.Routing"/>
    **<add namespace="DotNetNuke.Web.Mvc.Helpers"/>**
  </namespaces>
```

I tried commenting out the two bold lines, but I didn't notice a change in the behavior. (See attached screen shot, or go to Vashoneoc.org to view...)
![5-24-2016 at 1 04 46 pm](https://cloud.githubusercontent.com/assets/19364623/15518232/b56c6cd0-21b0-11e6-9915-8ada98afaf4b.jpg)

Now I'm wondering if there should be a dark image or some other mods to have the menu appear properly? Am I not finding the next level of doc perhaps?

THANKS for this awesome skin!

**Comment by VashonSoftware** [comment]
If I scroll down a bit, a dark banner comes into play which allows the menu to be seen. Maybe I just put a blank container at the top of the page, to prevent the overlaping images? Hmmm. Still exploring!

Where's Slide1.jpg referred to in the source, I'm not finding it...

**Comment by dnnconsulting** [comment]
Hi James, 

looks like you are using the home skin which has a transparent navbar. if you want to keep the transparent navbar you'll have to place an image or slider in the 'sliderpane', this is a full width pane so the image should be big enough to cover the whole width.

To place an image slider there have a look at this page on the DnnMDesign demo site http://www.dnnmdesign.com/Javascript/Carousel

If you don't want to have the transparent navbar switch the skin to the 'Host:DnnMDesign' skin

Regards,
Geoff.

**Comment by VashonSoftware** [comment]
For others wanting to get started, install the skin, and apply the skin to the page (via the page settings "appearance" area.

Then create a basic HTML module in the SliderPane area/pane of the web page. Edit the HTML module, switch to HTML mode, and paste in the code from the referenced http://www.dnnmdesign.com/Javascript/Carousel page. 

You need to edit the names (and paths) of the images used for the slider carousel there. I was able to get the nice hover and click effects, but for me it didn't advance to the 2nd image ever, but didn't fiddle with it much.

**Comment by dnnconsulting** [comment]
Hi again James,

I'm glad that you are sorting things out for yourself and your site.

1 of the main reasons for creating these OS themes is to stimulate people, like yourself, to dive in and learn how a Dnn theme is put together.

I would love to see the site that you are working on and maybe add it to a list on the theme site if this is ok?

Regards,
Geoff

**Comment by VashonSoftware** [comment]
Sorry, I'd be fine with that except this was a bit of a distraction (I moved to 8.0 with a solpartmenu that thus broke www.vashoneoc.org) and gave up on Mdesign for now as I'm on deadline, and the image I put in didn't connect right to the top, leaving part of the menu without anything beneath it. If I return to it (maybe for www.vashonbeprepared.org), I'll let you know. The design is awesome! Thx for your doing it!

Sent from my artphone

-------- Original message --------
