### ISSUE TITLE
Nav - Root Page with Subs

### ISSUE THREAD

**Issue by JaySMa** [dnnconsulting/DnnC.MDesign#2]
Hello..
Is there a way to make the navigation menu work so that if a page has sub-pages, the root page can be selected and visited?

Now, if a parent page has subpages, it can't be selected.  When moused-over, the sub-pages are shown and a click on the root page doesn't do anything.

Thanks..

**Comment by JaySMa** [comment]
Discovered that editing nav.cshtml allows the URL of the parent pages to work properly.

```
                if (node.Selected) { 
                    <li class="dropdown active"> 
                        <a href="@node.Url" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">@node.Text <span class="caret"></span></a>
                        @RenderChildNodes(node.Children)
                    </li>
                } else {
                    <li class="dropdown"> 
                        <a href="@node.Url" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@node.Text <span class="caret"></span></a>
                        @RenderChildNodes(node.Children)
                    </li>
                }
```

**Comment by JaySMa** [comment]
As with your DNNBooster skin, I copied the navs/default folder, named it clickable and made the above changes to the nav.cshtml file.

Then within the navbar.ascx file, made the menustyle="navs/clickable" change.

This works well.  Thanks..

**Comment by dnnconsulting** [comment]
Thats googd to hear Jaysma!
